
alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if [[ -d $HOME/.linuxbrew ]]; then
  export PATH="$HOME/.linuxbrew/bin:$PATH"
  export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
fi

if [[ -d $HOME/anaconda2 ]]; then
  export PATH="$HOME/anaconda2/bin:$PATH"
fi

if [[ -d /usr/local/cuda/lib64 ]]; then
  export PATH=/usr/local/cuda/bin:$PATH
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
  export CUDA_HOME=/usr/local/cuda
fi

[[ $- != *i* ]] && return

export CLICOLOR=1

if which fzf &> /dev/null
then
  source /usr/share/fzf/key-bindings.bash
fi

if which nnn &> /dev/null
then
  source /usr/share/nnn/quitcd/quitcd.bash_zsh
fi
