# This bashrc only contains essential stuff where zsh cannot be used.
try_source() {
  [[ -r $1 ]] && source $1
}

alias ls='ls --color=auto'
# PS1='[\u@\h \W]\$ '
PS1='\[\033[01;32m\]\u:\[\033[01;34m\]\w\[\033[00m\]\$ '

[[ $- != *i* ]] && return

HISTSIZE=1048576
SAVEHIST=1048576

export CLICOLOR=1

try_source /usr/share/fzf/key-bindings.bash
try_source /usr/share/nnn/quitcd/quitcd.bash_zsh
