try_source() {
  [[ -r $1 ]] && source $1
}

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
try_source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
try_source .antigen.zsh

if [[ -d $HOME/.linuxbrew ]]; then
  export PATH="$HOME/.linuxbrew/bin:$PATH"
  export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
fi

if [[ -d $HOME/anaconda2 ]]; then
  export PATH="$HOME/anaconda2/bin:$PATH"
fi

if [[ -d /usr/local/cuda/lib64 ]]; then
  export PATH=/usr/local/cuda/bin:$PATH
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
  export CUDA_HOME=/usr/local/cuda
fi


fpath=(~/.zsh/completion /usr/local/share/zsh/site-functions $fpath)

#base16
# BASE16_SHELL="$HOME/.config/base16-shell/"
# [ -n "$PS1" ] && \
#   [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
#   eval "$("$BASE16_SHELL/profile_helper.sh")"

# completion
autoload -U compinit
compinit

# load custom executable functions
for function in ~/.zsh/functions/*; do
  source $function
done

# makes color constants available
autoload -U colors
colors

# enable colored output from ls, etc
export CLICOLOR=1

# history settings
setopt hist_ignore_all_dups inc_append_history
HISTFILE=~/.zhistory
HISTSIZE=1048576
SAVEHIST=1048576

# awesome cd movements from zshkit
setopt autocd autopushd pushdminus pushdsilent pushdtohome cdablevars
DIRSTACKSIZE=5

# Enable extended globbing
setopt extendedglob

# Allow [ or ] whereever you want
unsetopt nomatch


# handy keybindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^K" kill-line
bindkey "^R" history-incremental-search-backward
bindkey "^P" history-search-backward
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word
bindkey -s "^T" "^[Isudo ^[A" # "t" for "toughguy"

# aliases
try_source ~/.aliases

if hash xclip 2> /dev/null; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi

# extra files in ~/.zsh/configs/pre , ~/.zsh/configs , and ~/.zsh/configs/post
# these are loaded first, second, and third, respectively.
_load_settings() {
  _dir="$1"
  if [ -d "$_dir" ]; then
    if [ -d "$_dir/pre" ]; then
      for config in "$_dir"/pre/**/*(N-.); do
        . $config
      done
    fi

    for config in "$_dir"/**/*(N-.); do
      case "$config" in
        "$_dir"/pre/*)
          :
          ;;
        "$_dir"/post/*)
          :
          ;;
        *)
          if [ -f $config ]; then
            . $config
          fi
          ;;
      esac
    done

    if [ -d "$_dir/post" ]; then
      for config in "$_dir"/post/**/*(N-.); do
        . $config
      done
    fi
  fi
}
_load_settings "$HOME/.zsh/configs"

if command -v brew &> /dev/null; then
  # nvm
  export NVM_DIR=~/.nvm
  # TODO slowest
  # try_source $(brew --prefix nvm)/nvm.sh
fi

if [[ -e /etc/arch-release ]]; then
  try_source /usr/share/fzf/key-bindings.zsh
  try_source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
  try_source /usr/share/nnn/quitcd/quitcd.bash_zsh
fi
if nnn -V &> /dev/null; then
  # -c only in cli
  # # -d detailed mode
  # -H show hidden
  # -E use $EDITOR
  # -x don't know
  export NNN_OPTS="cHEx"
  export NNN_BMS="h:$HOME;g:$HOME/git;d:$HOME/Downloads/"
  # export NNN_PLUG='f:finder;o:fzopen;p:mocplay;d:diffs;t:nmount;v:imgview'
  export NNN_COLORS='1234'
  # export NNN_COLORS='a1b2c3d'
  # export NNN_COLORS='8abd'
fi

try_source ~/.fzf.zsh

# Local config
try_source ~/.zshrc.local

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
try_source ~/.p10k.zsh
