" Plugin-free vimrc. Fallback for when vim is invoked directly
" (not through the nvim alias). Mirrors the nvim config, minus
" anything that depends on plug.vim / installed plugins.

""""""""""""""" HELPER
function! InsertTabWrapper()
  let col = col('.') - 1
  if !col || getline('.')[col - 1] !~ '\k'
    return "\<tab>"
  else
    return "\<c-p>"
  endif
endfunction

set foldtext=Foldy()

function! Foldy()
  let linelen = &tw ? &tw : 80
  let marker  = strpart(&fmr, 0, stridx(&fmr, ',')) . '\d*'
  let range   = foldclosedend(v:foldstart) - foldclosed(v:foldstart) + 1

  let left    = substitute(getline(v:foldstart), marker, '', '')
  let leftlen = len(left)

  let right    = range . ' [' . v:foldlevel . ']'
  let rightlen = len(right)

  let tmp    = strpart(left, 0, linelen - rightlen)
  let tmplen = len(tmp)

  if leftlen > len(tmp)
    let left    = strpart(tmp, 0, tmplen - 4) . '... '
    let leftlen = tmplen
  endif

  let fill = repeat(' ', linelen - (leftlen + rightlen))

  return left . fill . right . repeat(' ', 100)
endfunction


""""""""""""""" CONTROL
let mapleader = " "

nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

inoremap jk <esc>

" spelling
map <leader>sn ]s
map <leader>sN [s
map <leader>sa zg
map <leader>s? z=

map <Leader>ct :!ctags -R .<CR>

map 0 ^
map gy "+y

cnoremap %% <c-r>=expand("%:h")<cr>/

map <Leader>p :set paste!<cr>

map <C-n> :cnext<CR>
map <C-m> :cprevious<CR>
nnoremap <leader>a :cclose<CR>


""""""""""""""" VISUAL
set hls
set backspace=2
set ruler
set showcmd
set laststatus=2
set cursorline
set lazyredraw

set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

set textwidth=80
set colorcolumn=+1

set relativenumber
set numberwidth=1

set list listchars=tab:»·,trail:·,nbsp:·

let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors

syntax on
silent! colorscheme desert


""""""""""""""" SETTING
set autowrite
set nobackup
set nowritebackup
set noswapfile
set history=5000
set incsearch
set smartcase
set noerrorbells
set nojoinspaces
set whichwrap=h,l
set display=lastline,uhex
set updatetime=100

" Auto-reload buffers when files change on disk
set autoread
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI *
      \ if mode() !~ '\v(c|r.?|!|t)' && getcmdwintype() == '' | checktime | endif

set wildmode=list:longest,list:full
inoremap <Tab> <c-r>=InsertTabWrapper()<cr>
inoremap <S-Tab> <c-n>
set splitbelow
set splitright

set complete+=kspell
set diffopt+=vertical
if executable('zsh')
  set shell=zsh
endif

set spellfile=$HOME/.vim-spell-en.utf-8.add

set foldmethod=indent
set foldlevel=100
set scrolloff=3

set undofile
set undodir=~/.vimundo

set mouse=a


""""""""""""""" FILETYPE
filetype plugin indent on

autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd FileType markdown setlocal spell
autocmd BufRead,BufNewFile *.md setlocal textwidth=80

autocmd FileType gitcommit setlocal textwidth=72
autocmd FileType gitcommit setlocal spell

autocmd FileType css,scss,sass setlocal iskeyword+=-

autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=2 shiftwidth=2


""""""""""""""" MISC
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
  runtime! macros/matchit.vim
endif

augroup vimrcEx
  autocmd!
  autocmd BufReadPost *
        \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal g`\"" |
        \ endif
  autocmd BufRead,BufNewFile Appraisals set filetype=ruby
augroup END

if executable('ag')
  set grepprg=ag\ --nogroup\ --nocolor
endif
